### ISSUE TITLE
True color not being detected :(((((

### ISSUE THREAD

**Issue by shelldandy** [robertboloc/lolcatjs#11]
Same text file:

LOLCAT 🌈 

![lolcat](https://user-images.githubusercontent.com/7088511/28404251-258be746-6cee-11e7-8aeb-8f6521844a93.png)

VS

LOLCATJS 🖍 

![screen shot 2017-07-20 at 01 52 12](https://user-images.githubusercontent.com/7088511/28404268-2b325cb6-6cee-11e7-8c77-c1a8e32df5f3.png)

**Comment by shelldandy** [comment]
![screen shot 2017-07-20 at 01 53 48](https://user-images.githubusercontent.com/7088511/28404298-4988bb60-6cee-11e7-8357-c51a861876a2.png)

Terminal Status

**Comment by robertmarsal** [comment]
Solved in #12
