### ISSUE TITLE
Unable to load the sleep module (no animations available)

### ISSUE THREAD

**Issue by thisismygitrepo** [robertboloc/lolcatjs#23]
I'm on a Windows machine and the message `Unable to load the sleep module (no animations available)` is really inconvenient and I don't have way to suppress it even though I might not want animation. Can we have a fix?

Thanks.

**Comment by robertmarsal** [comment]
Hi @thisismygitrepo thanks for pointing this out. This is now fixed in version `2.4.2`. To see the error messages please use the new `--debug` flag.

**Comment by alanhogan** [comment]
This is an issue for me too, on macOS. `lolcatjs -v` despite a `brew upgrade` and the fact what `which lolcatjs` says `/opt/homebrew/bin/lolcatjs`.

Maybe you can release a new brew version? not sure how that works.

I’m going to `rm` that `lolcatjs` and install it with `pnpm` instead.

_Edited to avoid an incorrect brew formula name_

**Comment by robertmarsal** [comment]
Hi Alan, I'm afraid the brew version of `lolcat` is the original Ruby version. I have not published `lolcatjs` to brew. Installing via npm or alternatives is the only supported way at the moment. Thanks
